### ISSUE TITLE
Docker Compose - The bot crashes after receiving a command or a new event in the game.

### ISSUE THREAD

**Issue by Piekario** [lilith-discord-bot/lilith#21]
**Describe the bug**
The bot crashes after receiving a command or a new event in the game.

**To Reproduce**
1. Clone project from github
2. Build and run project using Docker Compose
3. Send command to bot using discord or wait for new event
5. Bot crash

**Screenshots**
![13f444483d15bfe914c953ea40e8f799](https://github.com/glazk0/lilith/assets/114659764/03655452-ce4c-4515-a675-581952c01fde)
![02c07bc8b7b9976e6587be4d5edf3571](https://github.com/glazk0/lilith/assets/114659764/80a4d90b-1888-47a5-b3e3-e336e68d677a)

**Additional context**
After launching the containers using Docker Compose and entering any command into the Discord bot on the server, I receive an error in the container logs: 
```
docker-bot-2       | PrismaClientKnownRequestError:
docker-bot-2       | Invalid `this.guilds.findUnique()` invocation in
docker-bot-2       | /bot/lib/db/postgresql/repository/Guild.js:21:43
docker-bot-2       |
docker-bot-2       |   18 async findOrCreate(guildId, skipCache) {
docker-bot-2       |   19     const cache = await this.client.cache.get(`guilds:${guildId}`);
docker-bot-2       |   20     if (!cache || !!skipCache) {
docker-bot-2       |   21         let guild = await this.guilds.findUnique(
docker-bot-2       | The table `public.Guild` does not exist in the current database.
docker-bot-2       |     at An.handleRequestError (/bot/node_modules/@prisma/client/runtime/library.js:174:6929)
docker-bot-2       |     at An.handleAndLogRequestError (/bot/node_modules/@prisma/client/runtime/library.js:174:6358)
docker-bot-2       |     at An.request (/bot/node_modules/@prisma/client/runtime/library.js:174:6237)
docker-bot-2       |     at async GuildRepository.findOrCreate (/bot/lib/db/postgresql/repository/Guild.js:21:25)
docker-bot-2       |     at async InteractionHandler.run (/bot/events/InteractionHandler.js:111:21)
docker-bot-2       |     at async EventHandler.run (/bot/events/EventHandler.js:69:9) {
docker-bot-2       |   code: 'P2021',
docker-bot-2       |   clientVersion: '4.15.0',
docker-bot-2       |   meta: { table: 'public.Guild' }
docker-bot-2       | }
```

Additionally, when a new event occurs in the game, the bot throws an error: 
```
docker-postgres-1  | 2023-06-20 01:04:34.825 UTC [126] ERROR:  relation "public.Guild" does not exist at character 63
docker-postgres-1  | 2023-06-20 01:04:34.825 UTC [126] STATEMENT:  SELECT "public"."Guild"."id", "public"."Guild"."guildId" FROM "public"."Guild" WHERE ("public"."Guild"."id") IN (SELECT "t0"."id" FROM "public"."Guild" AS "t0" INNER JOIN "public"."Event" AS "j0" ON ("j0"."guildId") = ("t0"."guildId") WHERE ("j0"."type" = $1 AND "t0"."id" IS NOT NULL)) OFFSET $2
docker-bot-2       | /bot/node_modules/@prisma/client/runtime/library.js:174
```

**Comment by glazk0** [comment]
Hello there! So, there is a hotfix for this since we need to actually fix this in our docker-compose, it's mainly cause the tables doesn't exist yet in the DB.

The things I would recommend is, you launch the bot, even if the bot is down, you do **npx prisma migrate dev --name Init** in the actual folder when the database is running. Then when it's done you should be able to make it run normally.

**Comment by glazk0** [comment]
Can you join our support ? We'll help you there.

**Comment by Piekario** [comment]
I managed to start the bot. I'm currently working on the Docker Compose for your project ;)

**Comment by blastbeng** [comment]
Sorry to reopen this. But I have solved this problem by using this Dockerfile:

```
FROM node:bullseye

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
         git

RUN git clone https://github.com/lilith-discord-bot/lilith /build

RUN mkdir /tmp/build

RUN cp /build/package.json /tmp/build/package.json

WORKDIR /tmp/build

RUN npm install
RUN mv /tmp/build/node_modules /build/node_modules

WORKDIR /build

RUN npx prisma generate
RUN npm run build
RUN npm prune --production


RUN cp -R /build/dist /bot
RUN cp -R /build/node_modules /bot/node_modules
RUN cp /build/package.json /bot/package.json

WORKDIR /bot

COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

ENTRYPOINT [ "./entrypoint.sh" ]
```

with this entrypoint.sh:

```
#!/usr/bin/env bash
cd /build
npx prisma migrate dev --name Init
cd /bot
npm start
```

and this docker-compose file:

version: "3"

```
services:
  lilith:
    container_name: lilith
    depends_on:
      - lilith-postgres
      - lilith-redis
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - TOKEN=${TOKEN}
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=63798
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
    image: lilith-discord-bot/lilith:1.0.0
    network_mode: host
  lilith-redis:
    container_name: lilith-redis
    image: redis:7.0.11
    # TODO: configure redis properly, either by using arguments or using a separate volume for configs.
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "63798:6379"
    volumes:
      - redisdata:/data

  lilith-postgres:
    container_name: lilith-postgres
    image: postgres:13.11
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - "54322:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  redisdata:
```

hope this helps
